name: Auto WireGuard Ping Test

on:
  schedule:
    # 每3小时运行一次 (0, 3, 6, 9, 12, 15, 18, 21点)
    - cron: '0 */3 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        
    - name: Install dependencies
      run: go mod download
      
    - name: Run WireGuard ping test
      run: go run .
      
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add results.csv
        git diff --staged --quiet || git commit -m "自动更新测试结果 - $(date '+%Y-%m-%d %H:%M:%S')"
        git push